[package]
name = "rsume"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
headless_chrome = "1.0.15"
json-resume = "0.2.0"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
tempfile = "3.12.0"
